"""empty message

Revision ID: 016d10adb11e
Revises: 
Create Date: 2020-06-23 21:47:21.882277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '016d10adb11e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strains',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('race', sa.String(length=128), nullable=True),
    sa.Column('medical', sa.String(length=500), nullable=True),
    sa.Column('positive', sa.String(length=500), nullable=True),
    sa.Column('negative', sa.String(length=500), nullable=True),
    sa.Column('flavors', sa.String(length=128), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strains')
    # ### end Alembic commands ###
