"""empty message

Revision ID: 470b95cf5c04
Revises: 
Create Date: 2020-06-22 23:52:22.893388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '470b95cf5c04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strains',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('race', sa.String(length=128), nullable=True),
    sa.Column('medical', sa.String(length=500), nullable=True),
    sa.Column('positive', sa.String(length=500), nullable=True),
    sa.Column('negative', sa.String(length=500), nullable=True),
    sa.Column('flavors', sa.String(length=128), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strains')
    # ### end Alembic commands ###
