"""empty message

Revision ID: b78f90cb5557
Revises: 
Create Date: 2020-06-20 20:53:39.679444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b78f90cb5557'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('race', sa.String(length=128), nullable=False),
    sa.Column('medical', sa.String(length=500), nullable=True),
    sa.Column('positive', sa.String(length=500), nullable=False),
    sa.Column('negative', sa.String(length=500), nullable=True),
    sa.Column('flavors', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strain')
    # ### end Alembic commands ###
